# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI/CD/

on:
  push:
    branches: [ "main" ]


jobs:
  build:

    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: |
            touch .env
            echo "${{ secrets.PARKWISE_ENV_FILE }}"  > .env
   
     # Check if parkwise process exists in PM2
    - name: Check if parkwise process exists
      id: check_parkwise
      run: |
          if pm2 list | grep -q "parkwise"; then
            echo "::set-output name=exists::true"
          else
            echo "::set-output name=exists::false"
          fi

      # Restart or start parkwise based on existence
    - name: Restart or start parkwise
      if: steps.check_parkwise.outputs.exists == 'true'
      run: pm2 restart parkwise --update-env --wait-ready
          
    - name: Start parkwise
      if: steps.check_parkwise.outputs.exists == 'false'
      run: pm2 start src/index.ts --interpreter ./node_modules/.bin/ts-node --name parkwise --wait-ready

      # Save PM2 configuration after changes
    - run: pm2 save

