name: Node.js CI/CD/

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
      
    - name: Check for dependency changes
      id: check-dependency-changes
      run: |
        git diff --quiet HEAD^ HEAD package-lock.json package.json || echo "dependencies_changed=true" >> $GITHUB_ENV

    - name: Install dependencies
      if: env.dependencies_changed == 'true'
      run: npm ci

    - name: Create .env file
      run: |
        touch .env
        echo "${{ secrets.PARKWISE_ENV_FILE }}" > .env
   
    - name: Check if parkwise process exists
      id: check_parkwise
      run: |
        if pm2 describe parkwise > /dev/null 2>&1; then
          echo "exists=true" >> $GITHUB_ENV
        else
          echo "exists=false" >> $GITHUB_ENV
        fi
      continue-on-error: true

    - name: Restart parkwise
      if: env.exists == 'true'
      run: pm2 restart parkwise --update-env --wait-ready

    - name: Start parkwise
      if: env.exists == 'false'
      run: pm2 start src/index.ts --interpreter ./node_modules/.bin/ts-node --name parkwise --wait-ready

    - name: Save PM2 configuration
      run: pm2 save
